"""initial papers table

Revision ID: f9f43c7a6ad0
Revises: 
Create Date: 2026-09-14 16:49:05.567201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f43c7a6ad0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('arxiv_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('authors', sa.JSON(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('pdf_url', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('sections', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('parser_used', sa.String(), nullable=True),
    sa.Column('parser_metadata', sa.JSON(), nullable=True),
    sa.Column('pdf_processed', sa.Boolean(), nullable=False),
    sa.Column('pdf_processing_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_arxiv_id'), 'papers', ['arxiv_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_arxiv_id'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
